services:
  - name: app
    type: web
    env: docker
    runtime: image
    image:
      url: docker.io/linkace/linkace:latest
    startCommand: ""
    plan: starter
    region: oregon
    envVars:
      - key: PORT
        value: "80"
    disk:
      name: app-app-storage-app-backups
      mountPath: /app/storage/app/backups
      sizeGB: 10
