services:
  - name: default
    type: web
    env: docker
    runtime: image
    image:
      url: docker.io/linkace/linkace:latest
    startCommand: ""
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: "80"
    disk:
      name: default-app-database-database-sqlite
      mountPath: /app/database/database.sqlite
      sizeGB: 10
