services:
  - name: default
    type: web
    env: docker
    runtime: image
    image:
      url: docker.io/ananthakumaran/paisa:latest
    startCommand: ""
    plan: starter
    region: oregon
    envVars:
      - key: PORT
        value: "7500"
    disk:
      name: default-root-documents-paisa-
      mountPath: /root/Documents/paisa/
      sizeGB: 10
